### ISSUE TITLE
Impossible de changer l'empacement de la bibliothèque

### ISSUE THREAD

**Issue by jbarascut** [314r/joliebulle#123]
J'ai voulu changer l'emplacement de la bibliothèque et le bouton changer n'ouvre aucune fenêtre.

Traceback (most recent call last):
  File "/usr/share/joliebulle/preferences.py", line 73, in changePushed
    self.d = QtGui.QFileDialog.getExistingDirectory(self,
AttributeError: module 'PyQt5.QtGui' has no attribute 'QFileDialog'

Désolé, je sais faire du python mais pas du QT ^^

**Comment by jbarascut** [comment]
Si je reclique une autre traceback

Traceback (most recent call last):
  File "/usr/share/joliebulle/preferences.py", line 73, in changePushed
    self.d = QtGui.QFileDialog.getExistingDirectory(self,
AttributeError: module 'PyQt5.QtGui' has no attribute 'QFileDialog'
/bin/joliebulle : ligne 5 : 16277 Aborted                 (core dumped)python3 main.py $@

Et le programme se ferme.

**Comment by 314r** [comment]
Ok, merci pour le retour. Il s'agit d'un petit bug lié à la migration vers qt5. La correction ne devrait pas poser de problème.

**Comment by jbarascut** [comment]
Parfait merci. J'essaye d'apporter ma contribution au logiciel :)

**Comment by flagos** [comment]
just made a pull request to propose a solution.

**Comment by 314r** [comment]
Fixed.
